altura = float(input('Informe a altura: '))
largura = float(input('Informe a largura: '))
area = (altura * largura)
print('A parede tem uma área de {} m².'.format(area))
print('Serão necessários {} Litros de tinta para pintar.'.format(area/2))
